[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[theme]
base = "dark"
primaryColor = "#2563EB"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#0F172A"
textColor = "#E8EDF7"
